name: Publicar en Pling

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual_version:
        description: 'Version (ej. v1.0.1) - Dejar en blanco si usas el ultimo Release'
        required: false
        default: ''

jobs:
  update-pling:
    runs-on: windows-2022 # Infraestructura Windows Server limpia
    steps:
      - name: Configurar Python en Windows Server
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar pling-publisher via PIP
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install pling-publisher

      - name: Obtener informacion del release
        shell: cmd
        run: |
          SET "INPUT_VERSION=${{ github.event.inputs.manual_version }}"
          
          IF NOT "%INPUT_VERSION%"=="" (
            SET "VERSION=%INPUT_VERSION%"
            SET "RELEASE_URL=${{ github.server_url }}/${{ github.repository }}/releases/tag/%INPUT_VERSION%"
          ) ELSE (
            SET "VERSION=${{ github.event.release.tag_name }}"
            SET "RELEASE_URL=${{ github.event.release.html_url }}"
          )
          
          echo VERSION=%VERSION%>>%GITHUB_ENV%
          echo RELEASE_URL=%RELEASE_URL%>>%GITHUB_ENV%

      - name: Publicar de verdad en Pling simulando el formulario
        shell: cmd
        env:
          USER_SECRET: ${{ secrets.PLING_USER }}
          PASS_SECRET: ${{ secrets.PLING_PASSWORD }}
          PROD_ID: ${{ vars.PRODUCT_ID }}
        run: |
          REM pling-publisher inicia sesion y fuerza los cambios saltandose el bug de la API
          REM Las variables %USER_SECRET% y %PASS_SECRET% no procesan el '$' de tu clave, pasa intacto
          python -m pling-publisher ^
            --user "%USER_SECRET%" ^
            --password "%PASS_SECRET%" ^
            --product "%PROD_ID%" ^
            --version "%VERSION%" ^
            --description "Icon pack updated to version %VERSION%. Download the latest assets directly from GitHub: %RELEASE_URL%"
